use core::{error::Result, run};

fn main() -> Result<()> {
    run()
}
